### ISSUE TITLE
no dist folder in v0.3.6 package

### ISSUE THREAD

**Issue by AxeMea** [jridgewell/sourcemaps#10] opened 2024-12-10 08:24 UTC
no dist folder in v0.3.6 package

**Comment by tyrann0us** [comment] 2024-12-10 08:27
Duplicate of all closed issues in this repository. Why do people not search?

**Comment by Criheacy** [comment] 2024-12-10 08:27
Causes tailwindcss failed to install:
```
tailwindcss` > sucrase > @jridgewell/gen-mapping@0.3.6: publish failed to build the dist directory
```

**Comment by femke77** [comment] 2024-12-10 08:28
Thank you! tailwindcss install is failing now

**Comment by inzanez** [comment] 2024-12-10 08:28
This is still unresolved, even if there are "closed" issues.

**Comment by SpintroniK** [comment] 2024-12-10 08:31
@jridgewell it also breaks @asyncapi/generator@2.x

**Comment by huseyinzorlu** [comment] 2024-12-10 08:31
it is fine now!

**Comment by FluffyDiscord** [comment] 2024-12-10 08:31
I have enforced the 0.3.5 version, but its still failing to find this module

**Comment by ClementBenezech** [comment] 2024-12-10 08:32
Same here, babel core and Tailwind are broken:

@babel/core > @babel/generator > @jridgewell/gen-mapping@0.3.6: publish failed to build the dist directory
warning react-scripts > @babel/core > @ampproject/remapping > @jridgewell/gen-mapping@0.3.6: publish failed to build the dist directory
warning react-scripts > tailwindcss > sucrase > @jridgewell/gen-mapping@0.3.6: publish failed to build the dist directory

**Comment by gengjiawen** [comment] 2024-12-10 08:32
0.3.7 fixed :)

**Comment by jridgewell** [comment] 2024-12-10 08:36
v0.3.7 is published now.

**Comment by tyrann0us** [comment] 2024-12-10 08:36
And now, before you all move on with your lives, consider supporting @jridgewell. This repo has 3 stargazers, but the library has 50 million (!) weekly downloads.

**Closed** 2024-12-10 08:36 UTC

**Comment by nondanee** [comment] 2024-12-10 08:38
```
node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js:1328
            const originalLine = originalSource[sourceLine] ||= [];
                                                            ^^^

SyntaxError: Unexpected token '||='
```

v0.3.7 failed in node 14

**Comment by himanshuDewangan** [comment] 2024-12-10 08:52
failed in node v14.21.3

**Comment by swapnilsparsh** [comment] 2024-12-10 08:58
Fix for Node.js 14: Run this command 👇🏻

```
npm install -D @jridgewell/gen-mapping@0.3.5
```

**Comment by jridgewell** [comment] 2024-12-10 09:06
I reset the npm latest tag back to 0.3.5. I'll publish a new version tomorrow that includes all the fixes.
